version: 0.2

phases:
  install:
    commands:
      - echo "Installing tools (curl + unzip + docker if needed)"
      - yum update -y
      - yum install -y unzip curl docker --allowerasing

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - IMAGE_NAME=ai-incident-response
      - IMAGE_TAG=latest
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME .
      - docker tag $IMAGE_NAME:latest $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
